### ISSUE TITLE
erratum in the document

### ISSUE THREAD

**Issue by ojxio** [go-gilbert/gilbert#47]
## watch action

[The documents](https://go-gilbert.github.io/gilbert/docs/actions/#watch-action) says a watch action's config likes

```yaml
version: 1.0
tasks:
  watch:
  - action: watch
    params:
      # ...
      job:
        mixin: build-and-run-server # job to execure, similar to manifest job syntax. required.
```

but in fact it should be 

```yaml
version: 1.0
tasks:
  watch:
  - action: watch
    params:
      # ...
      run: # change here
        mixin: build-and-run-server # job to execure, similar to manifest job syntax. required.
```

I tried to use a watch action by copying the config sample from its documents and I always failed.

I couldn't figure out what was going on until I read [config.go#L26](https://github.com/go-gilbert/gilbert/blob/master/actions/watch/config.go#L26)

## mixin

[The documents]() tells that a mixin config should be something like

```yaml
version: 1.0
  mixins:
    hello-world:
      - plugin: shell
        params:
          command: 'echo "hello world"'
      - plugin: build
```

but it actually should be

```yaml
version: 1.0
  mixins:
    hello-world:
      - action: shell  # change here
        params:
          command: 'echo "hello world"'
      - action: build  # and change here
```

I also couldn't realized it until I read the codes of the sdk [job.go#L41](https://github.com/go-gilbert/gilbert-sdk/blob/master/job.go#L41)
